{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app: gloo
    # allows namespace scoping for webhooks
    namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
{{- end}}